name: test
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      repository: 'edipoarg/mapa'
    - name: Install modules
      run: yarn
    - name: Run build
      run: npm run build
