name: test
on: pull_request
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run Vitest
      run: npm run test
